# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work +define+COCOTB_SIM -sv -timescale 1ns/1ps -mfcu +acc  /home/alessandro/Politecnico\ Di\ Torino\ Studenti\ Dropbox/Alessandro\ Marchei/GITHUB_proj/cannyEdge/src/conv_block.sv
vsim  -onfinish exit -pli /home/alessandro/miniconda3/envs/py3_32/lib/python3.7/site-packages/cocotb/libs/libcocotbvpi_modelsim.so   work.conv_block 
onbreak resume
run -all
quit
